### ISSUE TITLE
Mod resources don't seem to work 

### ISSUE THREAD

**Issue by akmaslov** [DarkShadow44/resourcehighlighter-dark#1]
Howdy! It looks like modded resources are no longer working. The appear in the table just fine, but the labels don't show up on the map. It does work properly for vanilla resources still.

**Comment by DarkShadow44** [comment]
Seems to work fine with the mods I tested. Can you give me a minimal set of mods to reproduce?

**Comment by akmaslov** [comment]
Got a repro with Nullius and its core dependencies:
https://mods.factorio.com/mod/nullius

**Comment by DarkShadow44** [comment]
Thanks for the report, I pushed a fix!
