### ISSUE TITLE
Greeting from the original mod author

### ISSUE THREAD

**Issue by vamalo** [DarkShadow44/resourcehighlighter-dark#10]
Thanks for taking over my old mod!  I like what you've done with it.  The glowing resource icons with the amounts shown look good.
Originally, I wanted to draw a circle around each ore deposit so the player could see the ore distribution and exact amount remaining by mousing over the deposit.  Unfortunately, there's no way to make a map tag transparent to mouse events, so I had to settle on a treasure box off to the side.  It's a shame that there's no way to access the game's internal ore patch data structures.  I looked over your changes to the code and there's a few things I don't understand.  I'll make separate issues for them when I hear back from you.  I also marked my old mod as deprecated on the mod portal.

**Comment by DarkShadow44** [comment]
Hello, glad you like it! And thanks for making it in the first place! :smile: 

> It's a shame that there's no way to access the game's internal ore patch data structures.

You mean to give the exact amount? That should be possible, but probably not very fast...

> I looked over your changes to the code and there's a few things I don't understand. I'll make separate issues for them when I hear back from you.

Sure thing, or feel free to ask here.

**Comment by vamalo** [comment]
Yeah, the exact amount.  You can calculate the exact amount in a script, but of course it's extremely slow.

Here's a list of things I found:

1.  It looks like you're duplicating the definition of "resourcehighlighter-toggle" inside the loop in data-final-fixes.lua.

2.  Why don't you test whether the result from add_chart_tag() is nil like I was doing?

3. It looks like you got rid of the on_surface_deleted event and replaced it with a surface-validity test inside of update_labels().  Since you're saving all of the chunk data in 'global' now, you should clean up the invalid surface data at that point:

if surface and surface.valid then
...
else
global.chunk_recs[surface.index]=nil
end

4. The highlight-all code you added has a redundant loop.  It should be

if settings.global["resourcehighlighter-highlight-all"].value then               
    player_rec.choices[name]=true
end

5. Why aren't you destroying the old chart tags inside of reset()?  If you clear player_recs without first destroying them, then the player will have to manually delete each one.

6. Inside of on_configuration_changed(), you're now basically doing the stuff I was originally doing inside of reset()--closing the GUIs and destroying the map tags.  Is there any reason why on_configuration_changed() and the rh_reset command should work differently?

Thanks again for maintaining my mod :)  You've saved me many hours of work responding to bug reports and debugging.

**Comment by vamalo** [comment]
Yes, the location and exact amount of each ore patch.  It's possible, yes, but it would eat up way too much UPS to be practical.

Here are a couple of things I found:

1. Why is the definition of "resourcehighlighter-toggle" inside the loop in data-final-fixes?  I think it should be defined once above the loop.
2. highlight-all has a redundant loop.  The code should be:

            if settings.global["resourcehighlighter-highlight-all"].value then
                    player_rec.choices[name]=true
            end

**Comment by DarkShadow44** [comment]
1) Yes, that's true. I'll address that.
2) Seems right, thanks.

I got another mail, but those things don't appear here. I'll still address them:

1) Yes, add_chart_tag can return nil. It wasn't checked in your version, though I should maybe add that check.
2) I might be missing a bit of cleanup, but most should be handled when the chunk is deleted. Not sure how much I leak, really, but it shouldn't be much.
3) Regarding reset, I never used that, so there might be issues. Not sure how useful that command is anyways. AFAIK it never deleted tags.
4) I should probably unify on_configuration_changed, rescan and reset. I don't think reset is needed anymore. Or what was the difference between reset and rescan?

**Comment by vamalo** [comment]
Yeah, I accidentally compared your version to an unreleased version of my mod, so most of the things I mentioned didn't make sense.  Sorry for the confusion.

2. Regarding the surface cleanup, I think an event like on_surface_deleted might be needed for a mod like Space Exploration that lets the user delete an entire surface.  I haven't tested it though.  on_chunk_deleted might be adequate.
3. The rh_reset command should fix any problems a user is having with the mod by cleaning up the mod's map tags and clearing its internal data.  It should work the same way as on_configuration_changed:

commands.add_command("rh_reset", {"resourcehighlighter_rescan_reset"}, function(event)
    for _,player in pairs(game.players) do
        if is_gui_open(player) then
            close_gui(player)
        end
    end
    reset()
end)

4. rh_rescan was supposed to be a limited version of rh_reset that the player could use if their mod created or destroyed an ore patch.  In practice, rh_reset works just as well and handles all situtations, so it's probably best to remove rh_rescan.
