### ISSUE TITLE
Request: Shortcut

### ISSUE THREAD

**Issue by ray1claw** [DarkShadow44/resourcehighlighter-dark#12]
Hi, I have a simple request:

`Add a shortcut button in the quick shortcuts menu`

Why?:
I have recently taken to playing Factorio on the Steam Deck only as it's very convenient and performant enough for decent sized bases. The down-side is, I'm wholly dependent on UI shortcuts to access mod features. And I miss this mod as I'm not able to use it in that context.

Let me know if I can help with anything. Cheers!

**Comment by DarkShadow44** [comment]
Will be added into next version.
