### ISSUE TITLE
Suggestions and feedback

### ISSUE THREAD

**Issue by ajklotz** [DarkShadow44/resourcehighlighter-dark#13]
- I think this mod should just stay as a resource highlighter. I don't need it to tell me what drill/pump I need to harvest the resource. I think the row of buttons (which dont do anything) could be done away with, saving lots of real estate on screen.
- It would be nice to have a slider bar in the UI that the user can set a threshold to only show highlighted resource above the limit for the resources that are enabled (checkbox)
- Ability to keep highlighted resources on map without Resource Highlighter dialog active.

**Comment by ajklotz** [comment]
Something like this :) 

https://imgur.com/a/JNTLMRi

**Comment by DarkShadow44** [comment]
> I think this mod should just stay as a resource highlighter. I don't need it to tell me what drill/pump I need to harvest the resource. I think the row of buttons (which dont do anything) could be done away with, saving lots of real estate on screen.

Not a fan of removing the ore names, when playing with mods they can be pretty useful.

> It would be nice to have a slider bar in the UI that the user can set a threshold to only show highlighted resource above the limit for the resources that are enabled (checkbox)

Resource slider: Added. Although not exactly like you planned. Please report back on what you think of that :)

> Ability to keep highlighted resources on map without Resource Highlighter dialog active.

Not sure how that would work. Not opposed, but how would you suggest we implement that?

**Comment by ajklotz** [comment]
> Not a fan of removing the ore names, when playing with mods they can be pretty useful.

No, sorry I think you misunderstood me. Keep the ore names, but remove the drill icons. I play SE with ghost on water mod, and this is what my Resource Highlighter looks like, lots of icons everywhere. 
https://imgur.com/a/RoVlEru
I think we just need the checkboxes and ore names. 

> Resource slider: Added. Although not exactly like you planned. Please report back on what you think of that :)

Looks like it works, although I feel there is a big UPS/FPS hit when sliding it. Not sure if there is a way to optimize that. Also, I think 1M as the max could be too small for some resource types. In Space Exploration, ore/fluid patches can be up to 30million. Some people might not care for a 1million resource. 

> Not sure how that would work. Not opposed, but how would you suggest we implement that?

Good question - I'm not sure really. Maybe if the dialog was smaller, I wouldn't care to keep it open while I do work, referring to a reduced UI :)

**Comment by DarkShadow44** [comment]
> I think we just need the checkboxes and ore names.

I see. I'll add that as a config, on by default.

> Looks like it works, although I feel there is a big UPS/FPS hit when sliding it. Not sure if there is a way to optimize that.

Might be, every single change forces a redraw. Maybe just apply the changes half a second after the player stopped dragging?

> so, I think 1M as the max could be too small for some resource types. In Space Exploration, ore/fluid patches can be up to 30million.

Yeah, I considered going higher, but since it's linear, it makes selecting low values harder. Like, when you have 30 million, you don't care about 29.990M, next lower could be 29M. But I'd have to think about how to generate a nice scale for that.

Like, lets's say we have 200 steps from 10k to 30M, what would those steps be? I don't want to hardcode them, and my head is too tired for math right now :smile:

**Comment by ajklotz** [comment]
> Might be, every single change forces a redraw. Maybe just apply the changes half a second after the player stopped dragging?

Sounds like that might help.

> Yeah, I considered going higher, but since it's linear, it makes selecting low values harder. Like, when you have 30 million, you don't care about 29.990M, next lower could be 29M. But I'd have to think about how to generate a nice scale for that.
> 
> Like, lets's say we have 200 steps from 10k to 30M, what would those steps be? I don't want to hardcode them, and my head is too tired for math right now 😄

I see, what if this would be a mod setting where the player can set the min/max of that slider?

**Comment by illham93** [comment]
I came here to suggest the exact same thing as ajklotz, it would be nice to have the option of hiding the drills. In vanilla it's fine but with SE/K2 plus ghost on water, you end up with 10 drill icons and so the box ends up being pretty large. So +1 to that suggestion. Otherwise I love the mod, every other resource highlighting mod I found just has the highlights on all the time, I like the ability to turn them on or off.

**Comment by DarkShadow44** [comment]
Should be all resolved for the next version. If "Ability to keep highlighted resources on map without Resource Highlighter dialog active" is still needed, please open a new issue.

**Comment by ajklotz** [comment]
> Should be all resolved for the next version. If "Ability to keep highlighted resources on map without Resource Highlighter dialog active" is still needed, please open a new issue.

It looks beautiful! I love it, good job. The slider progresses nicely too! 

I am running into some UPS issues when a new session starts, but I'll start a new discussion on that.
