### ISSUE TITLE
High UPS at session start

### ISSUE THREAD

**Issue by ajklotz** [DarkShadow44/resourcehighlighter-dark#15]
Hello, is there anyway to improve the UPS when a new session starts? mod-resourcehighlighter-dark is at 102.7/72/243 when looking at debug info. The resource rescan shows complete, but I'm still really low on UPS. Not sure if this related to the new UI update.

https://imgur.com/a/VKNcxlA

**Comment by DarkShadow44** [comment]
Could you share a save to reproduce?
Also, is this a new issue, or was this already the case with the last versions?

**Comment by DarkShadow44** [comment]
Just pushed a fix, does this help?

**Comment by gabfv** [comment]
I had the same issue but I wanted to say thanks for the super-quick fix. =)

**Comment by ajklotz** [comment]
It's looking better, thank you for the quick fix, great work. Sorry I couldnt get you a save faster, I was out and about.
