### ISSUE TITLE
Suggestion: Dynamic resource list based on current surface

### ISSUE THREAD

**Issue by ajklotz** [DarkShadow44/resourcehighlighter-dark#16]
Hello again! 

Currently, the resource highlighter will show all resources in the game. It would be cool if the Resource Highlighter dialog only shows the resources for the surface you are looking at. For example, in Space Exploration, we are provided a navigation satellite to remotely view our planets. If I'm on a planet that only has copper/oil/vitamilange, I'd like to only see those in the Resource Highlighter dialog, not all of the resources in the game.

**Comment by DarkShadow44** [comment]
Implemented, keep em coming :grin: 

I've got two more small improvements, but I need an answer in the forums, since I don't know how to implement that.

**Comment by ajklotz** [comment]
Wow, you are a rockstar. I'm going to tell everyone at the space exploration discord about this mod lol

**Comment by ajklotz** [comment]
I know this is issue closed, but the dialog will only refresh if the dialog is closed and reopened. Any chance of doing it while its open?

**Comment by DarkShadow44** [comment]
Sure, fixed for the next version
