### ISSUE TITLE
Suggestion to UI 

### ISSUE THREAD

**Issue by ajklotz** [DarkShadow44/resourcehighlighter-dark#17]
Some of the UI elements look a little clunky, for example, the "Show only above" section has a dragable UI bar that doesn't actually work. It looks like a standalone dialog box inside of a dialog. I also think that the title bar of the main dialog doesn't need that button looking raise it has. 

Here is my cheap whiteboard photo editing skills to give you an idea: 

https://imgur.com/a/UahZVN3

- Remove dialog looking box on title bar.
- Smaller font for "Show only above" text
  - I couldnt quite edit the Show only above text, but, i think it just needs to be smaller.
- Smaller close button 
- Remove draggable UI element from Show only above area.
- Possible adding an input box for the threshold, but not really necessary.

Some of these UI ideas are from raiguards mod, like Task List and Rate Calculator

**Comment by ajklotz** [comment]
You might find some handy info, but you probably already know about raiguards style guide, https://github.com/raiguard/Factorio-SmallMods/wiki/GUI-Style-Guide

**Comment by DarkShadow44** [comment]
No, didn't know about those yet, thanks. I pushed a new version, please test :smiley:

**Comment by ajklotz** [comment]
Ok! Excited to test, it’ll be a couple of hours before I get back home to try it out.

**Comment by ajklotz** [comment]
> No, didn't know about those yet, thanks. I pushed a new version, please test 😃

It looks amazing, thank you so much!
