### ISSUE TITLE
Crash when opening Resource Highlighter in Space Exploration 

### ISSUE THREAD

**Issue by ajklotz** [DarkShadow44/resourcehighlighter-dark#18]
In Space Exploration, the game crashes if you open Resource Highlighter while looking at the surface of a ship travelling. 

![image](https://user-images.githubusercontent.com/9448682/213841448-434ba4e5-1c9d-47e9-8207-88180cc0741f.png)

```
The mod Resource Highlighter (Dark's Version) (2.2.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event resourcehighlighter-dark::on_lua_shortcut (ID 36)
__resourcehighlighter-dark__/control.lua:433: attempt to index local 'zone' (a nil value)
stack traceback:
	__resourcehighlighter-dark__/control.lua:433: in function 'open_gui'
	__resourcehighlighter-dark__/control.lua:543: in function <__resourcehighlighter-dark__/control.lua:537>
```

**Comment by DarkShadow44** [comment]
Thanks for reporting, didn't consider that possibility. Probably just need to hide all resources in that case, will make an update soon. Although the UI might look a bit weird with 0 resources shown...

**Comment by ajklotz** [comment]
I didn't expect to see resources while on this particular surface, I was flying my ship and about to look at your UI while waiting during flight :)

**Comment by DarkShadow44** [comment]
Fixed for next version
