### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by phmalacher** [DarkShadow44/resourcehighlighter-dark#19]
You can delete this message after reading it!
Thanks for this little mod. I play with a mineral-super starved  world and it helped me see a few pixels of precious resources I missed :-)

**Comment by ajklotz** [comment]
I'm not gonna lie, I've been pushing refresh on this github page to see if any changes are coming up lol. Its a nice handy mod

**Comment by DarkShadow44** [comment]
You're welcome :smile:
FWIW, I mostly considered the mod done, so if you want changes feel free to suggest them. Although I put in a few of my own, as you see. :wink:
