### ISSUE TITLE
Non-recoverable error when modded resource no longer exists.

### ISSUE THREAD

**Issue by z0w13** [DarkShadow44/resourcehighlighter-dark#2]
I've disabled [Cargo Ships](https://mods.factorio.com/mod/cargo-ships) and when I open the Resource Highlighter GUI (Shift+H) the following error happens:

```
The mod Resource Highlighter (Dark's Version) (2.0.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event resourcehighlighter-dark::resourcehighlighter-toggle (ID 242)
Unknown item name: oil_rig
stack traceback:
	[C]: in function 'add'
	__resourcehighlighter-dark__/control.lua:395: in function 'open_gui'
	__resourcehighlighter-dark__/control.lua:444: in function <__resourcehighlighter-dark__/control.lua:439>
```

For now to work around this the following works:

1. Disable resource highlighter
2. Load your game without it enabled, and save
3. Enable resource highlighter again
4. Have fun actually seeing your resources again \o/

**Comment by DarkShadow44** [comment]
I'll look into it... When you don't hear back in a couple of days, feel free to give me a ping.

**Comment by z0w13** [comment]
Any news on this? Assuming you had the time & energy for it.

**Comment by z0w13** [comment]
Addendum: I've done some more testing, and running `/rh_reset` resolves the issue, however, the code for resetting on configuration change only runs if there's changes to Resource Highlighter, you might want to change this to also reset and/or rescan when other mods get disabled/enabled.

**Comment by DarkShadow44** [comment]
Well, a configuration can also remove ores, so we probably need to run the reset every time the config changes...
I pushed a change, would you mind testing a bit whether that
a) fixes the issue completely for you
b) causes any other issues?

**Comment by z0w13** [comment]
Disabled Space Ex on my world, issue is gone with the new version, seems to remove resources correctly now. 

Don't think it should cause any other issues, have not seen any yet at least.

**Comment by DarkShadow44** [comment]
Alright, pushed the update to the modportal.
