### ISSUE TITLE
IR3 fissures

### ISSUE THREAD

**Issue by ajklotz** [DarkShadow44/resourcehighlighter-dark#21]
Hey Dark, I recently started a new mod, Industrial Revolution 3, and I am noticing that the UI lists all of the fissures as "sour gas fissure" and their output resource in parentheses. These fissures are not being highlighted by the tool, assuming because IR3 doesn't have a set count for these fissures. Here is the information from the IR3 UI about these resources 
![image](https://user-images.githubusercontent.com/9448682/219794907-9e2529e3-cc0a-4d21-8d2b-761900dc94d9.png)

**Comment by DarkShadow44** [comment]
I'll look into it when I have time, probably this weekend.

**Comment by DarkShadow44** [comment]
The fissures are highlighted, but since they're shown as 10k, you need to have the "Show only above" slide set properly.
I fixed the gas fissure names in the latest version.
