### ISSUE TITLE
Locate ru

### ISSUE THREAD

**Issue by MikdadAgasiev** [DarkShadow44/resourcehighlighter-dark#23]
resourcehighlighter_title=Resource Highlighter
min_resource_label=Показывать только свыше
resourcehighlighter_check_all=Выделить все
resourcehighlighter_check_none=Очистить выбор
resourcehighlighter_refresh=Обновить
resourcehighlighter_scan_complete=Повторное сканирование ресурсов завершено
resourcehighlighter_reset_help=Перезапустить мод
resourcehighlighter_rescan_help=Повторное сканирование каждого блока (чанка) на наличие ресурсов
resourcehighlighter_scan_started=Повторное сканирование всех фрагментов... Это может занять несколько минут
resourcehighlighter-request-translation=__2__
resourcehighlighter_scan_percent=Повторное сканирование ресурса в__1__%

[controls]
resourcehighlighter-toggle=Вкл/выкл Resource Highlighter

[mod-setting-name]
resourcehighlighter-highlight-all=Выделить все по умолчанию
resourcehighlighter-show-miners=Показать возможное оборудование для добычи в пользовательском интерфейсе
resourcehighlighter-show-resource-results=Показать ресурс, который вы получите от добычи полезного ископаемого

[shortcut-name]
resourcehighlighter-toggle=Вкл/выкл Resource Highlighter

**Comment by DarkShadow44** [comment]
Would you mind making this a pull request?

**Comment by MikdadAgasiev** [comment]
I don't understand it. How to do it?)

**Comment by DarkShadow44** [comment]
Eh, it's alright. Can you update the translations to the newest changes? I'll add them soon.

**Comment by MikdadAgasiev** [comment]
resourcehighlighter_title=Resource Highlighter
min_resource_label=оказывать только свыше
resourcehighlighter_check_all=Выделить все ресурсы
resourcehighlighter_check_none=Очистить выбор
resourcehighlighter_refresh=Обновить
resourcehighlighter_scan_complete=Повторное сканирование ресурса завершено.
resourcehighlighter_reset_help=Сбросить настройки мода.
resourcehighlighter_rescan_help=Повторно сканировать каждый чанк на наличие ресурсов.
resourcehighlighter_scan_started=Повторное сканирование всех чанков... Это может занять несколько минут.
resourcehighlighter-request-translation=__2__
resourcehighlighter_scan_percent=Повторное сканирование ресурса в __1__%

[controls]
resourcehighlighter-toggle=Переключить выделение ресурсов

[mod-setting-name]
resourcehighlighter-highlight-all=Выделить все по умолчанию
resourcehighlighter-remember-selection=Запомнить выделение после закрытия пользовательского интерфейса (переопределяет настройку "выделить все")
resourcehighlighter-show-miners=Показать возможное оборудование для добычи в пользовательском интерфейсе
resourcehighlighter-show-resource-results=Показать ресурс, который вы получите от добычи полезного ископаемого

[shortcut-name]
resourcehighlighter-toggle=Вкл/выкл Resource Highlighter

**Comment by DarkShadow44** [comment]
Thanks, update is published!

**Comment by MikdadAgasiev** [comment]
Sorry, I just saw it now. I missed one capital letter (
At the beginning
min_resource_label=оказывать только свыше
Need to fix on
min_resource_label=Показывать только свыше

**Comment by DarkShadow44** [comment]
Alright, although I won't make an extra release for just this, it'll be part of the next one.
