### ISSUE TITLE
Support for RSO

### ISSUE THREAD

**Issue by LAGIdiot** [DarkShadow44/resourcehighlighter-dark#25]
I have question regarding support for RSO (https://mods.factorio.com/mod/rso-mod).

I have generated new map with RSO mod installed and Resource Highlighter is not showing any ores. I have tried rescan (/rh_reset) but still no ores gets highlighted.

Is this hard incompatibility between these two mods? Or just this scenario was not expected and for that reason there is no support and needs to be added?

**Comment by DarkShadow44** [comment]
Did you use shift-h to open the resource highlighter menu? Keep in mind that this mod doesn't highlight everything, only on demand while the menu is open.

**Comment by LAGIdiot** [comment]
I have opened it via icon previously but even when I have tried right now via hotkeys result is same - it does not work. And yes I know ho to use your mod as I used it in my previous lets play with no problems (but map was generated by default Factorio - not RSO).

I have even created new map just to test it and when ores are generated via RSO they just don't get highlighted.

**Comment by DarkShadow44** [comment]
Can you provide a sample map, including all mods and mod options?

**Comment by LAGIdiot** [comment]
Sure.

There is completely new map generated with just RSO and ResourceHighlighter mods and default configuration. As even on this simplest example highlighting does not work (and there are no other mods to interfere with it).

[RSO_w_ResourceHighlighter.zip](https://github.com/DarkShadow44/resourcehighlighter-dark/files/13776409/RSO_w_ResourceHighlighter.zip)

**Comment by DarkShadow44** [comment]
You don't happen to have "Show only above" set to high? Works perfectly for me.
![Screenshot_20231227_183709](https://github.com/DarkShadow44/resourcehighlighter-dark/assets/2029892/4f138c98-d406-45c8-8d69-621ad4445fbe)

**Comment by LAGIdiot** [comment]
Right now I have it set same way as you but:
![20231227210221_1](https://github.com/DarkShadow44/resourcehighlighter-dark/assets/3093101/dd7fc7bf-c8cf-44fb-9b53-9c5ebfd45719)

**Comment by LAGIdiot** [comment]
Oh, I have found out, I am an idiot...I don't have enabled tags on map.

Thanks for your help and I am really sorry about this.

**Comment by LAGIdiot** [comment]
Well maybe some tooltip that tags needs to be enabled would be good.
