### ISSUE TITLE
Error: Invalid surface name or index

### ISSUE THREAD

**Issue by serieznyi** [DarkShadow44/resourcehighlighter-dark#3]
Hi. You make a great mod. Thank you. 
But I got next error then use it.

Mod version: 2.0.4

Error text
```
Error while running event resourcehighlighter-dark::on_gui_checked_state_changed (ID 3)
Invalid surface name or index.
stack traceback:
	[C]: in function 'is_chunk_charted'
	__resourcehighlighter-dark__/control.lua:209: in function 'get_chunk_res'
	__resourcehighlighter-dark__/control.lua:244: in function 'search_chunk_res'
	__resourcehighlighter-dark__/control.lua:323: in function 'update_labels'
	__resourcehighlighter-dark__/control.lua:454: in function <__resourcehighlighter-dark__/control.lua:448>
```

Another mods what I use with yours mod:

![изображение](https://user-images.githubusercontent.com/2323142/114263572-054b8180-99ef-11eb-8427-4888ee71c13b.png)
![изображение](https://user-images.githubusercontent.com/2323142/114263576-12687080-99ef-11eb-9bc4-1edd6072a929.png)
![изображение](https://user-images.githubusercontent.com/2323142/114263579-1f855f80-99ef-11eb-9bf1-27ac9df6e43c.png)

**Comment by DarkShadow44** [comment]
Can you provide a save to reproduce the error?

**Comment by serieznyi** [comment]
Save file is to big for github, so I upload it on google drive. 

https://drive.google.com/file/d/1cxPOy1PVx0R_V6p9kINJWFjLAj4fy8LW/view?usp=sharing

I try reproduce error again and everything works fine. 
Except one time when Factorio is freezed.
So maybe you can`t find problem. 
I reopen this issue later if I take a crash again.

**Comment by serieznyi** [comment]
I can`t reproduce error
