### ISSUE TITLE
scan_chunk crash (2.0.4)

### ISSUE THREAD

**Issue by jouki** [DarkShadow44/resourcehighlighter-dark#4]
Here's the error throwing after loading the game (it crashes immediately):
<img width="412" alt="Screenshot_77" src="https://user-images.githubusercontent.com/1493141/126042601-0e2205a5-b61a-4faf-b227-77c4542ab93c.png">

here's the modlist:
[mod-list.txt](https://github.com/DarkShadow44/resourcehighlighter-dark/files/6834952/mod-list.txt)

here's the whole log:
[factorio-current.log](https://github.com/DarkShadow44/resourcehighlighter-dark/files/6834954/factorio-current.log)

**Comment by DarkShadow44** [comment]
Could you provide the save for this crash? I already had this crash, but could not reliably reproduce it.

**Comment by jouki** [comment]
Hey, sure: [www.mega.nz](https://mega.nz/file/Xo5F1QqC#11XZB45OlyueRRalj3HJBWmZgLkx5Hf4qvgyYZiPQEY
)

**Comment by DarkShadow44** [comment]
I uploaded a change to github. Can you test if that fixes it?

Also, for me there's a lot of resource labels. Those are not from my mod, correct?

**Comment by jouki** [comment]
Hey, it seems to be working.
Cheers
