### ISSUE TITLE
Incompatibility with chunk trimming

### ISSUE THREAD

**Issue by HentotheWen** [DarkShadow44/resourcehighlighter-dark#5]
Among other mods, the very popular space exploration mod relies on chunk trimming in order to keep the save files to a manageable level.  Resource highlighter crashes when it is used after chunks have been trimmed.  As a workaround, enabling and re-enabling the resource highlighter works.

**Comment by DarkShadow44** [comment]
Can you test the latest update from my github?

**Comment by HentotheWen** [comment]
New version works great! Thank you.

**Comment by HentotheWen** [comment]
It seemed to be working fine until I tried to highlight "all" on a planet
that was partially explored.
Great mod!  Hope you can fix it.. this is with SE, multiple surfaces, I
trimmed chunks and then explored some of them again.

**Comment by DarkShadow44** [comment]
What exactly happened, a crash? If so, can you post a crash log?

**Comment by HentotheWen** [comment]
Sure.

**Comment by DarkShadow44** [comment]
Should be fixed now, if not, please reopen.
