### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by d0ob** [DarkShadow44/resourcehighlighter-dark#6]
Hi there ! 

It doesn't work for me, I can open the GUI but it doesn't do anything. Is there any known incompatiblities ?
I can paste my mod list if needed, pretty sure I only have "enhanced map colors" map related thought.

Thanks.

**Comment by DarkShadow44** [comment]
It doesn't work when you check some ores in the GUI?
Did you make sure that map labels (Tags) are enabled? They can be disabled, similar to the pollution cloud.

**Comment by d0ob** [comment]
No, no I didn't enabled tags ^^ Indeed it works like a charme after that ! 
_Seems obvious now but I didn't tought of that, to me tags were player made.
Indeed, now I think of it I already saw mods using them, but I didn't realised..._
( Maybe it could be precised in the description, for the few noobs of my kind ^^ )

Well, thanks for the mod, nicely made and practical, and thanks for the quick answer !

**Comment by DarkShadow44** [comment]
Good to hear, I added a sentence about that into the mods description.

**Comment by d0ob** [comment]
Hi there ! =)
Since I already have your ears I wanted to ask something ^^

Do you think it would be doable to have a setting wich allow to set the default selection ?
I mean : For now it's opened on "none" by default, could it be opened on "all" if I prefer ? 
Because, on a fresh world, I want to see all, so it would be quicker if it was set at window opening.

But hey, I'm nitpicking ^^ Thanks for the description addition btw =)

PS: Would you want a translations ? I made one yesterday for another mod and I liked doing it, so I figured that I could gladly do them if of any use, as a "thank for the mod" ! (French translation, didn't even thought of saying lol)

**Comment by DarkShadow44** [comment]
A setting like that should be doable. Please open a separate ticket for that though.

If you want to do translations, sure think. It's just that I can't test those, since I don't speak French :D

**Comment by d0ob** [comment]
Yes indeed, I suppose you'd have to trust me xD
(edit: I think I half missunderstood what you said by testing it ^^ Well, to see legit words I installed the french version, so I could do the test ! )

Google trad it, it would give a hint about what I say ^^ I know in english I'm not the sharpest knife, lol but in french I try to have a nice wording and make no spell misstakes. (Everything is possible, but I re-read what I do multiple times on multiple day to make sure ^^ ) 

I think, modestly ^^ that I made a nice work previously, I go look at vanilla's game's french words if there is, I phrase it good while keeping the original sentences exact as possible. Call me professional amateurish translator lol 

I'll do it anyway, then post down there, you'll decide if you use it or not !

**Comment by d0ob** [comment]
I tried to be as faithful to the original while concise as possible, but french can be talkative tho (I certainly am lol) ; If lines are too long I can still make quicker. 

resourcehighlighter_title=Resource Highlighter
resourcehighlighter_check_all=Toutes
resourcehighlighter_check_none=Aucune
resourcehighlighter_refresh=Actualiser
resourcehighlighter_scan_complete=Nouveau scan complété.
resourcehighlighter_reset_help=Remise à zéro du mod.
resourcehighlighter_rescan_help=Scanner à nouveau les chunks à la recherche de ressources.
resourcehighlighter_scan_started=Nouveau scan des chunks...  Peut prendre plusieurs minutes.
resourcehighlighter-request-translation=__2__
resourcehighlighter_scan_percent=Nouveau scan de ressources complété à __1__%

[controls]
resourcehighlighter-toggle=Afficher Resource Highlighter

[mod-setting-name]
resourcehighlighter-minimum-size=Quantité minimale de ressources sous laquelle un filon ne sera pas pris en compte.

**Comment by DarkShadow44** [comment]
Thanks, translation included. You might want to review the translation for the new setting :P

**Comment by d0ob** [comment]
Oh nice ! I feel like a lazy fk for having asked you that xD 
But It's more convenient that way, I regret nothing ! ^^ Thanks much !! 

Oh, you made it ? The translation ? Yeah it's perfect ! Don't tell me you speak french I'll feel stupid xD
